"""initial schema

Revision ID: 0f5eed124d8f
Revises: 
Create Date: 2026-09-20 18:04:13.495883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel columns


# revision identifiers, used by Alembic.
revision: str = '0f5eed124d8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_slug'), ['slug'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_entity_id'), ['entity_id'], unique=False)

    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('angle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('talking_points', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pool', 'promoted', 'parked', 'dropped', name='ideastatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idea_status'), ['status'], unique=False)

    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('blog', 'linkedin', 'x', 'infographic', 'carousel', 'quote', 'other', name='piecetype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sa.Enum('not_started', 'draft', 'wip', 'ready', 'published', name='stage'), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piece_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_piece_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_piece_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_piece_stage'), ['stage'], unique=False)

    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_piece_id'), ['piece_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_piece_id'))

    op.drop_table('publication')
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piece_stage'))
        batch_op.drop_index(batch_op.f('ix_piece_idea_id'))
        batch_op.drop_index(batch_op.f('ix_piece_due_at'))
        batch_op.drop_index(batch_op.f('ix_piece_brand_id'))

    op.drop_table('piece')
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_status'))
        batch_op.drop_index(batch_op.f('ix_idea_brand_id'))

    op.drop_table('idea')
    op.drop_table('setting')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_event_entity'))

    op.drop_table('event')
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_slug'))

    op.drop_table('brand')
    # ### end Alembic commands ###
