"""piece: due_on date, drop folder and remind_at

Revision ID: 756c6cdb7be8
Revises: 0f5eed124d8f
Create Date: 2026-09-20 22:58:39.739588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel columns


# revision identifiers, used by Alembic.
revision: str = '756c6cdb7be8'
down_revision: Union[str, Sequence[str], None] = '0f5eed124d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_on', sa.Date(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_piece_due_at'))
        batch_op.create_index(batch_op.f('ix_piece_due_on'), ['due_on'], unique=False)
        batch_op.drop_column('folder')
        batch_op.drop_column('due_at')
        batch_op.drop_column('remind_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('due_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('folder', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_piece_due_on'))
        batch_op.create_index(batch_op.f('ix_piece_due_at'), ['due_at'], unique=False)
        batch_op.drop_column('due_on')

    # ### end Alembic commands ###
