"""piece: add slug

Revision ID: f8dfd0156432
Revises: 756c6cdb7be8
Create Date: 2026-09-20 23:41:49.232865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel columns


# revision identifiers, used by Alembic.
revision: str = 'f8dfd0156432'
down_revision: Union[str, Sequence[str], None] = '756c6cdb7be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is needed for rows that already exist; it is dropped again below so
    # the column matches the model, where the default lives in Python.
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='')
        )

    # Second pass: SQLite rebuilds the table for each batch block, so dropping the
    # default has to happen in its own block.
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.alter_column('slug', existing_type=sqlmodel.sql.sqltypes.AutoString(),
                              server_default=None, existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
