"""The files behind a piece.

Each piece owns a folder in the workspace. Drafts, images and anything Claude writes
live there, and the folder is self-contained so it can be moved or backed up on its own.
"""
from __future__ import annotations

from pathlib import Path

from sqlmodel import Session

from . import crud
from .dates import local_date
from .models import Idea, Piece
from .settings import get_settings


def piece_folder(session: Session, piece: Piece) -> Path:
    """`content/<brand>/<created date>-<slug>/`.

    Built from the creation date (on your calendar, not UTC's) and the slug fixed at
    creation, so renaming a piece later never moves files out from under an open session.
    """
    name = f"{local_date(piece.created_at).isoformat()}-{piece.slug}"
    return get_settings().content_dir / crud.brand_slug(session, piece.brand_id) / name


def ensure_folder(session: Session, piece: Piece) -> Path:
    folder = piece_folder(session, piece)
    (folder / "assets").mkdir(parents=True, exist_ok=True)
    return folder


def delete_piece(session: Session, piece: Piece) -> Path | None:
    """Delete a piece: its folder goes to the trash first, then its entry goes.

    Returns where the folder went, or None if it never had one. If the folder cannot be
    moved, this raises OSError and nothing is deleted — on Windows that happens while a
    terminal session is still open in it.
    """
    folder = piece_folder(session, piece)
    trashed = None
    if folder.exists():
        trashed = _move_to_trash(folder, crud.brand_slug(session, piece.brand_id))
    try:
        crud.delete_piece(session, piece)
    except Exception:
        if trashed:
            trashed.rename(folder)          # put the work back where the entry expects it
        raise
    return trashed


def _move_to_trash(folder: Path, brand: str) -> Path:
    """`trash/<brand>/<folder name>`, numbered if a folder of that name is already there.

    A rename rather than shutil.move: the trash is in the same workspace, so a rename either
    happens completely or not at all, where a copy could stop halfway.
    """
    target_dir = get_settings().trash_dir / brand
    target_dir.mkdir(parents=True, exist_ok=True)
    target, number = target_dir / folder.name, 2
    while target.exists():
        target, number = target_dir / f"{folder.name}-{number}", number + 1
    folder.rename(target)
    return target


def write_brief(session: Session, piece: Piece) -> Path:
    """Write `brief.md`: the facts a terminal session needs before it starts.

    Regenerated on every launch, so it always matches the database. Nothing here is
    hand-edited; notes belong on the piece or in the draft. The brand's voice and profile
    are copied in whole: the database is their only home, and this is how a session sees
    them.
    """
    folder = ensure_folder(session, piece)
    idea: Idea | None = crud.get_idea(session, piece.idea_id) if piece.idea_id else None
    brand = crud.get_brand(session, piece.brand_id)

    lines = [
        f"# {piece.title}",
        "",
        "Generated by Content Machine. Do not edit; it is rewritten on every launch.",
        "",
        "## This piece",
        f"- Type: {piece.type.name}",
        f"- Stage: {piece.stage.value}",
        f"- Due: {piece.due_on.isoformat() if piece.due_on else 'not scheduled'}",
        f"- Brand: {brand.name} ({brand.slug})",
        f"- Piece id: {piece.id}  (use `cm stage {piece.id} <stage>` when the stage changes)",
    ]
    if piece.notes:
        lines += ["", "### Notes", piece.notes]

    if idea:
        lines += ["", "## The idea behind it", f"**{idea.title}**"]
        if idea.angle:
            lines += ["", f"Angle: {idea.angle}"]
        if idea.talking_points:
            lines += ["", "### Talking points", idea.talking_points]
        if idea.mode:
            lines += ["", f"### Mode: {idea.mode.name}",
                      idea.mode.description.strip()
                      or "This mode has no description yet. Ask me what it means before drafting."]
        if idea.notes:
            lines += ["", "### Idea notes", idea.notes]

    siblings = crud.list_pieces(session, idea_id=idea.id) if idea else []
    others = [p for p in siblings if p.id != piece.id]
    if others:
        lines += ["", "## Other pieces from this idea"]
        lines += [f"- {p.type.name} — {p.stage.value}" for p in others]

    # The brand's own documents go last, as they have headings of their own.
    if brand.voice.strip():
        lines += _document("Voice", brand.voice)
    else:
        lines += ["", "## Voice", "",
                  "No voice written for this brand yet. Ask me for the voice before drafting."]
    if brand.profile.strip():
        lines += _document("Brand profile", brand.profile)

    brief = folder / "brief.md"
    brief.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return brief


def _document(title: str, text: str) -> list[str]:
    """A document written in the app, copied in whole. Its headings would otherwise read as
    sections of the brief, so start and end lines show exactly where it begins and stops."""
    name = title.lower()
    return ["", f"## {title}", "",
            f"----- start of the {name}, as written in the app -----", "",
            text.strip(), "",
            f"----- end of the {name} -----"]
