"""The files behind a piece.

Each piece owns a folder in the workspace. Drafts, images and anything Claude writes
live there, and the folder is self-contained so it can be moved or backed up on its own.
"""
from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path

from sqlmodel import Session

from . import crud
from .models import Idea, Piece
from .settings import get_settings


def piece_folder(session: Session, piece: Piece) -> Path:
    """`content/<brand>/<created date>-<slug>/`.

    Built from the creation date and the slug fixed at creation, so renaming a piece
    later never moves files out from under an open terminal session.
    """
    name = f"{_local_date(piece.created_at).isoformat()}-{piece.slug}"
    return get_settings().content_dir / crud.brand_slug(session, piece.brand_id) / name


def _local_date(moment: datetime) -> date:
    """Folder names use your calendar date, not UTC's.

    Times are stored as UTC; SQLite hands them back without a timezone, so one is attached
    before converting.
    """
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    return moment.astimezone().date()


def ensure_folder(session: Session, piece: Piece) -> Path:
    folder = piece_folder(session, piece)
    (folder / "assets").mkdir(parents=True, exist_ok=True)
    return folder


def brand_voice_file(session: Session, piece: Piece) -> Path | None:
    path = get_settings().brands_dir / crud.brand_slug(session, piece.brand_id) / "voice.md"
    return path if path.exists() else None


def write_brief(session: Session, piece: Piece) -> Path:
    """Write `brief.md`: the facts a terminal session needs before it starts.

    Regenerated on every launch, so it always matches the database. Nothing here is
    hand-edited; notes belong on the piece or in the draft.
    """
    folder = ensure_folder(session, piece)
    idea: Idea | None = crud.get_idea(session, piece.idea_id) if piece.idea_id else None
    voice = brand_voice_file(session, piece)

    lines = [
        f"# {piece.title}",
        "",
        "Generated by Content Machine. Do not edit; it is rewritten on every launch.",
        "",
        "## This piece",
        f"- Type: {piece.type.value}",
        f"- Stage: {piece.stage.value}",
        f"- Due: {piece.due_on.isoformat() if piece.due_on else 'not scheduled'}",
        f"- Brand: {crud.brand_slug(session, piece.brand_id)}",
        f"- Piece id: {piece.id}  (use `cm stage {piece.id} <stage>` when the stage changes)",
    ]
    if piece.notes:
        lines += ["", "### Notes", piece.notes]

    if idea:
        lines += ["", "## The idea behind it", f"**{idea.title}**"]
        if idea.angle:
            lines += ["", f"Angle: {idea.angle}"]
        if idea.talking_points:
            lines += ["", "### Talking points", idea.talking_points]
        if idea.mode:
            lines += ["", f"Mode: {idea.mode}"]
        if idea.notes:
            lines += ["", "### Idea notes", idea.notes]

    lines += ["", "## Voice"]
    lines += [f"Follow `{voice}`." if voice else
              "No voice file for this brand yet. Ask me for the voice before drafting."]

    siblings = crud.list_pieces(session, idea_id=idea.id) if idea else []
    others = [p for p in siblings if p.id != piece.id]
    if others:
        lines += ["", "## Other pieces from this idea"]
        lines += [f"- {p.type.value} — {p.stage.value}" for p in others]

    brief = folder / "brief.md"
    brief.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return brief
